# Generated by Django 4.2.9 on 2026-03-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dus_api", "0002_librarydocument_dusexamquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarydocument",
            name="page_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="librarydocument",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Bekliyor"),
                    ("processing", "İşleniyor"),
                    ("done", "Tamamlandı"),
                    ("error", "Hata"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="librarydocument",
            name="text_content",
            field=models.TextField(blank=True),
        ),
    ]
