# Generated by Django 5.2.12 on 2026-03-28 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dus_api", "0003_library_pdf_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="image_cards/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("pending", "Onay Bekliyor"),
                            ("published", "Yayında"),
                            ("rejected", "Reddedildi"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="image_cards",
                        to="dus_api.chapter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_cards",
                        to="dus_api.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_image_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "image_cards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("entity_type", models.CharField(blank=True, max_length=30)),
                ("entity_id", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action"], name="user_activi_user_id_46cf8f_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="user_activi_user_id_c742e0_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="user_activi_entity__08d33e_idx",
                    ),
                ],
            },
        ),
    ]
