# Generated by Django 5.2.12 on 2026-03-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dus_api", "0004_imagecard_useractivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="commission_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=20.0, max_digits=5, null=True
            ),
        ),
    ]
