# Generated by Django 4.2.9 on 2026-03-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dus_api", "0005_user_commission_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="auto_renew",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="renewed_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewals",
                to="dus_api.subscription",
            ),
        ),
    ]
