# Generated by Django 4.2.9 on 2026-03-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dus_api", "0006_subscription_auto_renew"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
